### ISSUE TITLE
Python Error when canceling the input process

### ISSUE THREAD

**Issue by ivanbusthomi** [ivanbusthomi/cdf_converter#1]
### Problem

After defining a valid netcdf file, when defining it again but canceling it midway, will raise this error

```
RuntimeError: Failed to parse NETCDF: prefix string into expected 2, 3 or 4 fields. 
Traceback (most recent call last):
  File "C:/Users/busthi/.qgis2/python/plugins\CDFconverter\cdf_converter_dialog.py", line 85, in on_select_subdataset_currentIndexChanged
    self.get_bands()
  File "C:/Users/busthi/.qgis2/python/plugins\CDFconverter\cdf_converter_dialog.py", line 91, in get_bands
    netcdf_sd = gdal.Open(netcdf_sd_path)
RuntimeError: Failed to parse NETCDF: prefix string into expected 2, 3 or 4 fields.
```

**Comment by ivanbusthomi** [comment]
fixed in this commit: https://github.com/ivanbusthomi/cdf_converter/commit/3e97407a0f8b5e2c841d64968e8d66638ba279af
